### ISSUE TITLE
Error Code SQLITE_LOCKED (6): Database Is Locked

### ISSUE THREAD

**Issue by gottsohn** [rawberg/connect-sqlite3#15]
This error occurs infrequently when using `express-session`

**Comment by wmertens** [comment]
The problem is probably that you are using multiple workers? I'm seeing the same, only when using multiple workers.

The solution would be to set the session db to use WAL mode. This does change it to be 3 files instead of one.

To do this manually, do this from the command line:
```
$ sqlite3 sessions.db 'pragma journal_mode=wal;'
wal
```

You can do this while your app is running. From then on, it should be fine.
